// GENERATED from the Android Palettes.kt by tools/convert_palettes.py - do not edit by hand.
// The 11 hand-tuned pond palettes, identical color values on both platforms.

import SwiftUI

extension PondPalette {
    static let duskPond = PondPalette(
        isDark: true,
        background: Color(hex: 0x0B2733),
        backgroundHigh: Color(hex: 0x0F3242),
        surface: Color(hex: 0x123A4C),
        surfaceHigh: Color(hex: 0x1A4A5F),
        outline: Color(hex: 0x2A607A),
        textPrimary: Color(hex: 0xEAF7FC),
        textSecondary: Color(hex: 0x8FBCCB),
        accent: Color(hex: 0xFFC94D),
        water: Color(hex: 0x17607F),
        waterDeep: Color(hex: 0x104A64),
        waterRim: Color(hex: 0x3E93B5),
        ripple: Color(hex: 0xBDEBFF),
        rock: Color(hex: 0x7C8A93),
        rockDark: Color(hex: 0x55626B),
        pad: Color(hex: 0x3FA35C),
        padDark: Color(hex: 0x2C7A44),
        duck: Color(hex: 0xFFD44D),
        duckShade: Color(hex: 0xF0B437),
        beak: Color(hex: 0xFF8A3D),
        turtle: Color(hex: 0x6BA46B),
        turtleShell: Color(hex: 0x4A7D52),
        current: Color(hex: 0x9FDCF2),
        star: Color(hex: 0xFFC94D),
        danger: Color(hex: 0xFF6B6B),
    )

    static let sunnyMorning = PondPalette(
        isDark: false,
        background: Color(hex: 0xEAF6FB),
        backgroundHigh: Color(hex: 0xDDEFF7),
        surface: Color(hex: 0xFFFFFF),
        surfaceHigh: Color(hex: 0xF2FAFF),
        outline: Color(hex: 0xA5CBDC),
        textPrimary: Color(hex: 0x123647),
        textSecondary: Color(hex: 0x4E7A8C),
        accent: Color(hex: 0xFFB300),
        water: Color(hex: 0x6FC7E8),
        waterDeep: Color(hex: 0x58B8DD),
        waterRim: Color(hex: 0x2E8FB5),
        ripple: Color(hex: 0xFFFFFF),
        rock: Color(hex: 0x9AA7B0),
        rockDark: Color(hex: 0x76838C),
        pad: Color(hex: 0x4CBF6B),
        padDark: Color(hex: 0x379A52),
        duck: Color(hex: 0xFFD23F),
        duckShade: Color(hex: 0xEFB52D),
        beak: Color(hex: 0xFF8A3D),
        turtle: Color(hex: 0x74B36F),
        turtleShell: Color(hex: 0x52905A),
        current: Color(hex: 0xEFFCFF),
        star: Color(hex: 0xFFB300),
        danger: Color(hex: 0xE85D5D),
    )

    static let sakuraPond = PondPalette(
        isDark: false,
        background: Color(hex: 0xFDEEF3),
        backgroundHigh: Color(hex: 0xFBE2EA),
        surface: Color(hex: 0xFFFFFF),
        surfaceHigh: Color(hex: 0xFFF5F8),
        outline: Color(hex: 0xE5B7C8),
        textPrimary: Color(hex: 0x4A2432),
        textSecondary: Color(hex: 0x96687A),
        accent: Color(hex: 0xE8618C),
        water: Color(hex: 0xEFB9CF),
        waterDeep: Color(hex: 0xE6A7C2),
        waterRim: Color(hex: 0xC97FA4),
        ripple: Color(hex: 0xFFFFFF),
        rock: Color(hex: 0xB0989F),
        rockDark: Color(hex: 0x8E767D),
        pad: Color(hex: 0x7FBF8E),
        padDark: Color(hex: 0x5FA070),
        duck: Color(hex: 0xFFD44D),
        duckShade: Color(hex: 0xF0B437),
        beak: Color(hex: 0xFF8A3D),
        turtle: Color(hex: 0x86AE84),
        turtleShell: Color(hex: 0x628C64),
        current: Color(hex: 0xFFF0F5),
        star: Color(hex: 0xFFC94D),
        danger: Color(hex: 0xD94F6E),
    )

    static let midnightNeon = PondPalette(
        isDark: true,
        background: Color(hex: 0x0A0A14),
        backgroundHigh: Color(hex: 0x121222),
        surface: Color(hex: 0x16162A),
        surfaceHigh: Color(hex: 0x1F1F3A),
        outline: Color(hex: 0x3A3A6A),
        textPrimary: Color(hex: 0xEDEDFF),
        textSecondary: Color(hex: 0x8B8BC0),
        accent: Color(hex: 0x00E5C7),
        water: Color(hex: 0x1B1B3E),
        waterDeep: Color(hex: 0x14142F),
        waterRim: Color(hex: 0x5A4FE0),
        ripple: Color(hex: 0x00E5C7),
        rock: Color(hex: 0x4A4A66),
        rockDark: Color(hex: 0x333349),
        pad: Color(hex: 0x2FDD73),
        padDark: Color(hex: 0x1FA854),
        duck: Color(hex: 0xFFE14D),
        duckShade: Color(hex: 0xE5C230),
        beak: Color(hex: 0xFF9046),
        turtle: Color(hex: 0x5AC8A8),
        turtleShell: Color(hex: 0x3B9A7E),
        current: Color(hex: 0x7B6CFF),
        star: Color(hex: 0xFFE14D),
        danger: Color(hex: 0xFF4D6D),
    )

    static let autumnGold = PondPalette(
        isDark: true,
        background: Color(hex: 0x241407),
        backgroundHigh: Color(hex: 0x2E1B0C),
        surface: Color(hex: 0x382210),
        surfaceHigh: Color(hex: 0x452B15),
        outline: Color(hex: 0x6B4A26),
        textPrimary: Color(hex: 0xFFF3E0),
        textSecondary: Color(hex: 0xC9A276),
        accent: Color(hex: 0xFFA726),
        water: Color(hex: 0x8C5A24),
        waterDeep: Color(hex: 0x74491C),
        waterRim: Color(hex: 0xC08840),
        ripple: Color(hex: 0xFFE0B2),
        rock: Color(hex: 0x8D7B6B),
        rockDark: Color(hex: 0x6B5B4D),
        pad: Color(hex: 0x8FA032),
        padDark: Color(hex: 0x6F7E24),
        duck: Color(hex: 0xFFD44D),
        duckShade: Color(hex: 0xEDB93B),
        beak: Color(hex: 0xE86A2A),
        turtle: Color(hex: 0x97A45C),
        turtleShell: Color(hex: 0x737F41),
        current: Color(hex: 0xFFD9A0),
        star: Color(hex: 0xFFC94D),
        danger: Color(hex: 0xFF6B5E),
    )

    static let frozenPond = PondPalette(
        isDark: false,
        background: Color(hex: 0xE8F3FA),
        backgroundHigh: Color(hex: 0xDCEBF5),
        surface: Color(hex: 0xFFFFFF),
        surfaceHigh: Color(hex: 0xF2FAFF),
        outline: Color(hex: 0xB0CFE0),
        textPrimary: Color(hex: 0x17384E),
        textSecondary: Color(hex: 0x5C8298),
        accent: Color(hex: 0x2FA8E0),
        water: Color(hex: 0xBFE4F5),
        waterDeep: Color(hex: 0xACD9EF),
        waterRim: Color(hex: 0x7FB8D6),
        ripple: Color(hex: 0xFFFFFF),
        rock: Color(hex: 0x9FB4C2),
        rockDark: Color(hex: 0x7E93A1),
        pad: Color(hex: 0x6FCF97),
        padDark: Color(hex: 0x52AD79),
        duck: Color(hex: 0xFFD44D),
        duckShade: Color(hex: 0xF0B437),
        beak: Color(hex: 0xFF8A3D),
        turtle: Color(hex: 0x7FAE9E),
        turtleShell: Color(hex: 0x5C8A7B),
        current: Color(hex: 0xFFFFFF),
        star: Color(hex: 0xFFC107),
        danger: Color(hex: 0xE57373),
    )

    static let jungleMist = PondPalette(
        isDark: true,
        background: Color(hex: 0x0D2415),
        backgroundHigh: Color(hex: 0x12301C),
        surface: Color(hex: 0x173A23),
        surfaceHigh: Color(hex: 0x1F4A2E),
        outline: Color(hex: 0x2F6B42),
        textPrimary: Color(hex: 0xEAFBEF),
        textSecondary: Color(hex: 0x93C4A2),
        accent: Color(hex: 0xFFD54F),
        water: Color(hex: 0x1E6B4A),
        waterDeep: Color(hex: 0x175539),
        waterRim: Color(hex: 0x48A57C),
        ripple: Color(hex: 0xC9F7DD),
        rock: Color(hex: 0x8A9186),
        rockDark: Color(hex: 0x636A60),
        pad: Color(hex: 0x9CCC4E),
        padDark: Color(hex: 0x77A437),
        duck: Color(hex: 0xFFD44D),
        duckShade: Color(hex: 0xF0B437),
        beak: Color(hex: 0xFF8A3D),
        turtle: Color(hex: 0x7FB069),
        turtleShell: Color(hex: 0x5B8549),
        current: Color(hex: 0xB6EFC9),
        star: Color(hex: 0xFFD54F),
        danger: Color(hex: 0xFF6B6B),
    )

    static let galaxyNight = PondPalette(
        isDark: true,
        background: Color(hex: 0x120A26),
        backgroundHigh: Color(hex: 0x1A1033),
        surface: Color(hex: 0x221540),
        surfaceHigh: Color(hex: 0x2C1C52),
        outline: Color(hex: 0x4A3380),
        textPrimary: Color(hex: 0xF2ECFF),
        textSecondary: Color(hex: 0xA898CF),
        accent: Color(hex: 0xFF7BD5),
        water: Color(hex: 0x2E2260),
        waterDeep: Color(hex: 0x241A4C),
        waterRim: Color(hex: 0x7B5FD0),
        ripple: Color(hex: 0xB39DFF),
        rock: Color(hex: 0x5C5470),
        rockDark: Color(hex: 0x423C52),
        pad: Color(hex: 0x3FD08A),
        padDark: Color(hex: 0x2BA46A),
        duck: Color(hex: 0xFFE14D),
        duckShade: Color(hex: 0xE5C230),
        beak: Color(hex: 0xFF9046),
        turtle: Color(hex: 0x64B5A0),
        turtleShell: Color(hex: 0x468A78),
        current: Color(hex: 0x9DA8FF),
        star: Color(hex: 0xFFE14D),
        danger: Color(hex: 0xFF5C8A),
    )

    static let candyPop = PondPalette(
        isDark: false,
        background: Color(hex: 0xFFF3F8),
        backgroundHigh: Color(hex: 0xFFE7F1),
        surface: Color(hex: 0xFFFFFF),
        surfaceHigh: Color(hex: 0xFFF8FB),
        outline: Color(hex: 0xE8B5D2),
        textPrimary: Color(hex: 0x4C2440),
        textSecondary: Color(hex: 0x9A6A88),
        accent: Color(hex: 0xFF5FA2),
        water: Color(hex: 0x8FD8E8),
        waterDeep: Color(hex: 0x7BCBDE),
        waterRim: Color(hex: 0x3FA7C2),
        ripple: Color(hex: 0xFFFFFF),
        rock: Color(hex: 0xB8A2C8),
        rockDark: Color(hex: 0x957FA6),
        pad: Color(hex: 0x66D08A),
        padDark: Color(hex: 0x48AB6C),
        duck: Color(hex: 0xFFD23F),
        duckShade: Color(hex: 0xEFB52D),
        beak: Color(hex: 0xFF8A3D),
        turtle: Color(hex: 0x7CC29A),
        turtleShell: Color(hex: 0x5A9D77),
        current: Color(hex: 0xFFFFFF),
        star: Color(hex: 0xFFB300),
        danger: Color(hex: 0xE85D5D),
    )

    static let royalLagoon = PondPalette(
        isDark: true,
        background: Color(hex: 0x0D231C),
        backgroundHigh: Color(hex: 0x122D24),
        surface: Color(hex: 0x17372C),
        surfaceHigh: Color(hex: 0x1F4536),
        outline: Color(hex: 0x336650),
        textPrimary: Color(hex: 0xF3FBF2),
        textSecondary: Color(hex: 0x9CC4AE),
        accent: Color(hex: 0xF5C84C),
        water: Color(hex: 0x1B5E48),
        waterDeep: Color(hex: 0x154A39),
        waterRim: Color(hex: 0x4CA983),
        ripple: Color(hex: 0xFFE9A6),
        rock: Color(hex: 0x8C8F84),
        rockDark: Color(hex: 0x64675D),
        pad: Color(hex: 0xA3CE54),
        padDark: Color(hex: 0x7FA83C),
        duck: Color(hex: 0xFFD44D),
        duckShade: Color(hex: 0xF0B437),
        beak: Color(hex: 0xFF8A3D),
        turtle: Color(hex: 0x76AC80),
        turtleShell: Color(hex: 0x548760),
        current: Color(hex: 0xC8EED6),
        star: Color(hex: 0xF5C84C),
        danger: Color(hex: 0xFF6B6B),
    )

    static let coralReef = PondPalette(
        isDark: true,
        background: Color(hex: 0x062A2E),
        backgroundHigh: Color(hex: 0x0A363B),
        surface: Color(hex: 0x0E4249),
        surfaceHigh: Color(hex: 0x145059),
        outline: Color(hex: 0x27707B),
        textPrimary: Color(hex: 0xE8FBF9),
        textSecondary: Color(hex: 0x86BFC1),
        accent: Color(hex: 0xFF7F66),
        water: Color(hex: 0x0F5E66),
        waterDeep: Color(hex: 0x0B4C53),
        waterRim: Color(hex: 0x35A3AC),
        ripple: Color(hex: 0xB2FFF4),
        rock: Color(hex: 0xD07862),
        rockDark: Color(hex: 0xA65342),
        pad: Color(hex: 0x3FBF7F),
        padDark: Color(hex: 0x2C9560),
        duck: Color(hex: 0xFFD44D),
        duckShade: Color(hex: 0xF0B437),
        beak: Color(hex: 0xFF8A3D),
        turtle: Color(hex: 0x6BB597),
        turtleShell: Color(hex: 0x47906F),
        current: Color(hex: 0x9FF2E0),
        star: Color(hex: 0xFFD166),
        danger: Color(hex: 0xFF6B6B),
    )

    /// Warm gold on still green water - earned by clearing bonus ponds.
    static let goldenPond = PondPalette(
        isDark: true,
        background: Color(hex: 0x2A1F0C),
        backgroundHigh: Color(hex: 0x362813),
        surface: Color(hex: 0x43331A),
        surfaceHigh: Color(hex: 0x534023),
        outline: Color(hex: 0x8A6B34),
        textPrimary: Color(hex: 0xFFF6E2),
        textSecondary: Color(hex: 0xCDAE79),
        accent: Color(hex: 0xFFD166),
        water: Color(hex: 0x3C6B4A),
        waterDeep: Color(hex: 0x2F583C),
        waterRim: Color(hex: 0xB08A3E),
        ripple: Color(hex: 0xFFE9B0),
        rock: Color(hex: 0x9A8360),
        rockDark: Color(hex: 0x6F5C41),
        pad: Color(hex: 0x8FBF4C),
        padDark: Color(hex: 0x6C9636),
        duck: Color(hex: 0xFFCE3D),
        duckShade: Color(hex: 0xE0A824),
        beak: Color(hex: 0xFF8A3D),
        turtle: Color(hex: 0x87A45C),
        turtleShell: Color(hex: 0x63803F),
        current: Color(hex: 0xFFE1A0),
        star: Color(hex: 0xFFD166),
        danger: Color(hex: 0xFF7A5C),
    )
}
